services:
  network-deploy-service:
    networks:
      - bank-network
  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 1024m
    volumes:
      - ./libs/opentelemetry-javaagent-2.22.0.jar:/app/libs/opentelemetry-javaagent-2.22.0.jar:ro
    environment:
      JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/opentelemetry-javaagent-2.22.0.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none


  microservice-configserver-config:
    extends:
      service: microservice-base-config
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
