
build.version="3.0"

accounts.message=Welcome to Bank accounts related QA APIs
accounts.contactDetails.name=Smith Ray - QA Engineer
accounts.contactDetails.email=smith@bank.com
accounts.onCallSupport[0]=(666) 555-1234
accounts.onCallSupport[1]=(666) 523-1345