spring.config.activate.on-profile=prod

build.version="1.0.0"

accounts.message=Welcome to Bank accounts related Production APIs
accounts.contactDetails.name=John Patron - Product Owner
accounts.contactDetails.email=john@bank.com
accounts.onCallSupport[0]=(453) 555-1234
accounts.onCallSupport[1]=(236) 523-1345