
loans.message=Welcome to Bank loans related Production APIs
loans.contactDetails.name=John Patron - Product Owner
loans.contactDetails.email=john@bank.com
loans.onCallSupport[0]=(453) 555-1234
loans.onCallSupport[1]=(236) 523-1345