
build.version="3.0"

loans.message=Welcome to Bank loans related QA APIs
loans.contactDetails.name=Smith Ray - QA Engineer
loans.contactDetails.email=smith@bank.com
loans.onCallSupport[0]=(666) 555-1234
loans.onCallSupport[1]=(666) 523-1345