spring.config.activate.on-profile=prod

build.version="1.0.0"

cards.message=Welcome to Bank cards related Production APIs
cards.contactDetails.name=John Patron - Product Owner
cards.contactDetails.email=john@bank.com
cards.onCallSupport[0]=(453) 555-1234
cards.onCallSupport[1]=(236) 523-1345