
build.version="3.0"

cards.message=Welcome to Bank cards related QA APIs
cards.contactDetails.name=Smith Ray - QA Engineer
cards.contactDetails.email=smith@bank.com
cards.onCallSupport[0]=(666) 555-1234
cards.onCallSupport[1]=(666) 523-1345