spring.application.name=gatewayserver

spring.config.import=optional:configserver:http://localhost:8071

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.httpclient.connect-timeout=1000
spring.cloud.gateway.server.webflux.httpclient.response-timeout=10s

spring.data.redis.connect-timeout=2s
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=1s


spring.cloud.gateway.server.webflux.routes[0].id=accounts_custom_route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ACCOUNTS
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/eazybank/accounts/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/eazybank/accounts/(?<segment>.*), /${segment}

management.endpoints.web.exposure.include=*
management.health.readinessstate.enabled=true
management.health.livenessstate.enabled=true
management.endpoint.health.probes.enabled=true

management.endpoint.gateway.access=unrestricted

management.metrics.tags.application=${spring.application.name}



info.app.name=${spring.application.name}
info.app.description=API Gateway Server
info.app.version=1.0.0

logging.level.com.bank.gatewayserver=DEBUG
logging.pattern.level="%5p [${spring.application.name},%X{trace_id},%X{span_id}]"



resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10000
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=2


